[platformio]
default_envs = m5stack-cardputer

[env:m5stack-cardputer]
platform = espressif32
board = m5stack-stamps3
framework = arduino
monitor_speed = 115200
lib_deps =
  m5stack/M5Cardputer
  m5stack/M5Unified
  m5stack/M5GFX
build_flags =
  -DCORE_DEBUG_LEVEL=0
  -DDICE_VESSEL_VERSION=\"1.0.0\"
  -std=gnu++17
